networks:
  clickhouse_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.60.0.0/24

services:
  webtds_clickhouse:
    container_name: webtds_clickhouse
    image: "ccr.ccs.tencentyun.com/jxwaf/clickhouse-server:22.8.5-alpine"
    ports:
      - "9000:9000"
      - "9004:9004"
    environment:
      CLICKHOUSE_DB: wtds
      CLICKHOUSE_USER: jxlog_user
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
      CLICKHOUSE_PASSWORD: jxlog_password
      TZ: Asia/Shanghai
    volumes:
      - /opt/wtds_data/clickhouse:/var/lib/clickhouse
    restart: unless-stopped
    networks:
      clickhouse_network:
        ipv4_address: 172.60.0.10

  webtds_jxlog:
    container_name: webtds_jxlog
    image: "ccr.ccs.tencentyun.com/jxwaf/webtds-jxlog:v1.0"
    ports:
      - "8866:8866"
    environment:
      CLICKHOUSE: 172.60.0.10:9000  
      DATABASE: wtds
      USERNAME: jxlog_user
      PASSWORD: jxlog_password
      TABLE: wtds_log
      TCPSERVER: 0.0.0.0
      TZ: Asia/Shanghai
    depends_on:
      - webtds_clickhouse
    restart: unless-stopped
    networks:
      clickhouse_network:
        ipv4_address: 172.60.0.11
